version: 2
jobs:
  one:
    docker:
      - image: circleci/php:latest
    steps:
      - checkout
      - run: echo "first circle ci"
  two:
    docker:
      - image: circleci/php:latest
    steps:
      - checkout
      - run: echo "second circle ci after first circle ci"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - one
      - two:
          requires:
            - one